name: Action Workflow

on: [push]

jobs:
  action-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: Files Before Checkout
        run: |
          pwd
          ls -a

      - name: Checkout
        uses: actions/checkout@v4

      - name: Files After Checkout
        run: |
          pwd
          ls -a