name: Action Workflow

on: 
  push:
    branches:
      - main
    #   - '!test'

    # tags:
    #   - v1.*

    # paths: 
    #   - '**.js'
    #   - 'docs/*'
    #   - '!docs/file.txt'

jobs:
  action-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: Files Before Checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo "${{ github.token }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Files After Checkout
        run: |
          pwd
          ls -a