name: Default Environment Variables Workflow

on: push

jobs:
  default-env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Testing secret
        run: |
          echo "My Secret is $SECRET1"
        env:
          SECRET1: ${{ secrets.TEST }}



      - name: Environment Variables
        run: |
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "HOME": ${HOME}
          echo "GITHUB_WORKSPACE": ${GITHUB_WORKSPACE}
          echo "GITHUB_ACTIONS": ${GITHUB_ACTIONS}
          echo "GITHUB_API_URL": ${GITHUB_API_URL}
          echo "GITHUB_EVENT_PATH": ${GITHUB_EVENT_PATH}
          echo "GITHUB_JOB": ${GITHUB_JOB}
          echo "GITHUB_REPOSITORY": ${GITHUB_REPOSITORY}
          echo "GITHUB_SHA": ${GITHUB_SHA}
          echo "RUNNER_OS": ${RUNNER_OS}