name: Matrix Workflow

on: push

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    steps:
      - name: Default Node Version used
        run: node -v

      - uses: actions/setup-node@v3
        with: 
          node-version: 8

      - name: After setup node version
        run: node -v

      
