name: Matrix Workflow

on: push

jobs:
  matrix-job:
    strategy:
      matrix:
        node-version: [10,11,12]

    runs-on: ubuntu-latest
    steps:
      - name: Default Node Version used
        run: node -v

      - uses: actions/setup-node@v3
        with: 
          node-version: {{ matrix.node-version }}

      - name: After setup node version
        run: node -v

      
