name: Matrix Workflow

on: push

jobs:
  matrix-job:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [10,11,12]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Default Node Version used
        run: node -v

      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: After setup node version
        run: node -v

      
