name: New Workflow

on: 
  # schedule:
  #   - cron: "* * * * *"

  # push:
  #   branches: ["main"]

  pull_request:
    # branches: ["main"]
    types: [closed, assigned, opened, reopened]

jobs: 
  testing-sample-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: echo "Hello world"

      - name: script to run shell commands
        run: |
          node -v
          npm -v  

      - name: Step 2 
        run: echo "This is step 2"

      - name: Step 3 
        run: echo "This is step 3"