name: New Workflow

on: 
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs: 
  testing-sample-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: echo "Hello world"

      - name: script to run shell commands
        run: |
          node -v
          npm -v  